name: Python CI

on:
  push:
    branches:
      - main # or your main branch name like 'master'
    paths: # Only run CI if relevant files change (optional)
      - '**.py'
      - '**.yaml'
      - 'requirements.txt'
      - 'setup.py'
      - '.github/workflows/ci.yml'
  pull_request:
    branches:
      - main # or your main branch name like 'master'
    paths: # Only run CI if relevant files change (optional)
      - '**.py'
      - '**.yaml'
      - 'requirements.txt'
      - 'setup.py'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest # Use a standard runner OS

    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11'] # Test with different Python versions

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        # Optional: Use a dependency cache for faster builds
        cache: 'pip'
        cache-dependency-path: requirements.txt # Cache based on requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install core dependencies from requirements.txt
        pip install -r requirements.txt
        # Install test dependencies (assuming you have extras_require['test'] in setup.py)
        pip install .[test]

    - name: Run tests with pytest
      run: |
        pytest -v # -v for verbose output