# .github/workflows/ci.yml

name: CI

on:
  push:
    branches:
      - main # Or your default branch name like 'master'
  pull_request:
    branches:
      - main # Or your default branch name like 'master'

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use a recent Ubuntu version

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Use v4 for checking out code

    - name: Set up Python
      uses: actions/setup-python@v5 # Use v5 for setting up Python
      with:
        python-version: '3.x' # Use a compatible Python version, e.g., '3.9', '3.10', '3.11'

    - name: Install dependencies
      # This step ensures dependencies are installed from requirements.txt
      # The `-m pip install --upgrade pip` part ensures pip is up-to-date
      # The `-r requirements.txt` part installs everything from your requirements file
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Add a step to install your package itself
    # This is necessary for imports like 'from noise.reset_error import ...' to work correctly
    - name: Install package
      run: pip install .

    - name: Run tests
      # Use python -m pytest to run your test suite
      run: |
        python -m pytest

    # Optional: Add linting or formatting checks (uncomment if you want them)
    # - name: Run linter (flake8)
    #   run: |
    #     # Install flake8 if not in requirements.txt
    #     # pip install flake8
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

